spring.application.name=payment-api

# サーバーのポート番号（Renderなどの環境に対応するため環境変数を優先します）
server.port=${PORT:8080}

# KOMOJUの非公開鍵（★ここを自分の鍵に書き換える！）
komoju.secret-key=${KOMOJU_SECRET_KEY:}

# H2 Database Settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/shopdb;AUTO_SERVER=TRUE}
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (Optional, allows you to see the DB at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never

app.mail.mock-enabled=true

# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=your_email@gmail.com
# spring.mail.password=your_app_password
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB